project_root: "."

lhpr_task_root: "/home/js/Desktop/datasets/lhpr/task"
lhpr_step_task_root: "/home/js/Desktop/datasets/lhpr/step_task"
lhpr_episode_task_root: "/home/js/Desktop/datasets/lhpr/episode_task"

hm3d_root: "/home/js/Desktop/datasets/hm3d"

output_root: "outputs"
report_root: "outputs/reports"
frame_root: "outputs/frames"
video_root: "outputs/replay_videos"